// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azolpholrzdashejgcdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6b2xwaG9scnpkYXNoZWpnY2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODUxNzQsImV4cCI6MjA3NDM2MTE3NH0.cGZB5l-ochueL1bQuWCUGrH0UaFMUZk6E6-3Qy9OmVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});